version: '3.8'

services:
  setup_db:
    build:
      context: ./database
    volumes:
      - ./database:/app
      - /app/node_modules
      - ../:/host
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    volumes:
      - ./rabbitmq/rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq-log:/var/log/rabbitmq
      - ./rabbitmq/init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/init/definitions.json:/etc/rabbitmq/definitions.json:ro

